import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import Provider from "@/components/Provider";
import { lazy, Suspense } from "react";
import Loading from "@/components/Loading";
import LayoutLoader from "@/components/LayoutLoader";

const LazyProvider = lazy(() => import("@/components/Provider"));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutLoader>
          <header className="sticky -top-8 z-50 bg-background space-y-1">
            <p className="w-full bg-zinc-500 text-center py-1">
              Premium Dry Fruits, Carefully Selected for You
            </p>
            <Nav />
          </header>

          <LazyProvider>
            <main className="h-full pt-4 space-y-10">
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </main>
          </LazyProvider>

          <Toaster />

          <footer className="lg:px-20 px-10 bg-[#D6A67F]/20 backdrop-blur-2xl py-10 mt-10">
            <Footer />
          </footer>
        </LayoutLoader>
      </body>
    </html>
  );
}
