export const newArrivalProducts: Product[] = [
  {
    name: "Kashmir Walnuts in Shell ",
    maxPrice: 1000,
    image: "/wallnut.png",
    minPrice: 500,
    catchLine: "|Kashmiri| Sabut Akhrot ,Walnuts with Shell",
  },
  {
    name: "Original Kashmiri Mamra Almonds",
    maxPrice: 2000,
    image: "/almonds.png",
    minPrice: 1000,
    catchLine: " Premium Quality, Protein-Rich Almonds",
  },
  {
    name: "Red Chilli Powder",
    maxPrice: 300,
    minPrice: 250,
    image: "/redchilliPowder.png",
    off: 17,
    catchLine: " Mild, Flavorful, and Aromatic",
  },
  {
    name: "Pure Kashmiri Honey",
    maxPrice: 400,
    minPrice: 200,
    image: "/honey.png",
    catchLine: "Experience the Rich Flavor",
  },
  {
    name: "Pure kasmiri Apricot",
    maxPrice: 400,
    minPrice: 0,
    image: "/apricot.png",
    catchLine: " Premium Quality, Protein-Rich Apricot",
  },
  {
    name: "Kashmiri Almonds by Al Fajer Mart ",
    maxPrice: 1000,
    minPrice: 500,
    image: "/almonds.png",
    catchLine: "Premium Quality, Protein-Rich Nuts",
  },
  {
    name: "Kashmiri Rosted Walnuts",
    maxPrice: 1000,
    minPrice: 500,
    image: "/rostedWallnut.png",
    catchLine: "Discover the Health Benefits of Pure Kashmiri Walnuts",
  },
  {
    name: "Kashmiri- Garlic | Lasun",
    maxPrice: 1600,
    minPrice: 800,
    image: "/garlic-pack.png",
    off: 50,
    catchLine: "Discover the Health Benefits of Pure Kashmiri Garlic | Lasun",
  },
];
